name: Update Kobo Data

on:
  schedule:
    - cron: '*/1 * * * *'  # Jalankan setiap 15 menit
  push:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install requests

      - name: Run Data Fetch Script
        run: python fetch_kobo_data.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data.json
          git commit -m "Update data from Kobo Toolbox"
          git push
